sudo: false
dist: trusty
language: node_js
node_js:
  - '6'
  - '7'
  - 'node'

notifications:
  email: false
  
env:
  - CXX=g++-4.8
cache:
  directories: node_modules
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - g++-4.8
      
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  
before_script:
- npm install -g codecov
#- npm install coveralls
#- ng lint
#- ng build
#- ng serve & ng e2e

script:
 - ng test --watch=false --code-coverage
 
after_success:
 - codecov
 - cat ./coverage/coverage.lcov | ./node_modules/coveralls/bin/coveralls.js
