sudo: false
language: node_js
node_js:
  - '6'
  - '7'
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g typescript angular-cli karma
  - npm install
script: ng test --watch=false --code-coverage
